# unforgettable7_game/unforgettable7/Makefile.toml
# https://github.com/sagiegurari/cargo-make

[config]
skip_core_tasks = true

[tasks.default]
description = "help for prepared make tasks"
clear = true
script= [
"printf ",
"printf COMMANDS AND MAKE TASKS:",
"printf ",
"printf $ clear - clear the screen",
"printf $ cargo make - this list",
"printf ",
"printf $ cargo make check - check code errors without compiling",
"printf $ cargo make release - build release version, increment semver patch in Cargo.toml",
"printf ",
"printf $ cargo make test - test the test code",
"printf $ cargo make udeps - cargo +nightly udeps - unused dependencies",
"printf $ cargo crev verify - always verify you dependencies",
"printf $ cargo make audit - RustSec advisories",
"printf $ cargo make doc - includes from Cargo.toml to README.md and from README.md to main.rs or lib.rs, generates doc and copies to docs folder, exports codetour to .md.",
"printf ",
]

# end of help
# end of help
# end of help

[tasks.check]
description = "cargo check --release"
script = [
    "printf $ cargo fmt",
    "cargo fmt",
    "printf $ cargo check --release",
    "cargo check --release",
]

# end of dev scripts
# end of dev scripts
# end of dev scripts

[tasks.release]
description = "cargo build release"
script = [
    # Binaries version is date
    "printf $ lmake_version_from_date",
    "lmake_version_from_date",
    "printf $ cargo fmt",
    "cargo fmt",
    "printf $ wasm-pack build --target web --release --no-typescript",
    "wasm-pack build --target web --release --no-typescript",
    #"printf $ rm -r pkg/snippets/*",
    #"rm -r pkg/snippets/*",
    "printf copy pkg/ to webfolder/pkg/",
    "\\rsync -a --info=progress2 --delete-after pkg/  ../webfolder/unforgettable7/pkg/",
]

# end of release scripts
# end of release scripts
# end of release scripts

[tasks.test]
description = "cargo test"
clear = true
script = [
    "printf $ cargo test",
    "cargo test",
]

[tasks.udeps]
description = "lists unused dependencies needs nightly"
clear = true
script = [
	"cargo +nightly udeps",
]

[tasks.verify]
description = "cargo crev verify - "
clear = true
script = [
    "cargo crev verify"
]

[tasks.audit]
description = "cargo audit - RustSec advisories"
clear = true
script = [
    "cargo audit"
]

[tasks.doc]
description = "cargo doc - create docs from doc comments"
clear = true
script= [
    "printf $ lmake_lines_of_code",
    "lmake_lines_of_code",
    "printf $ lmake_cargo_toml_to_md",
    "lmake_cargo_toml_to_md",
    "printf $ lmake_md_to_doc_comments",
    "lmake_md_to_doc_comments",
    "printf $ cargo doc --no-deps --document-private-items",
    # create doc from doc comments
    "cargo doc --no-deps --document-private-items",
    "printf $ codetour_export_to_md",
    # export code tour to md
    "codetour_export_to_md",
    # copy to /docs/ because it is github standard
    # message to help user with next move
    "printf after successful doc, run cargo make commit msg_for_commit",
]

# end of git script
# end of git script
# end of git script
